spring.application.name=Event Organiser 


spring.datasource.url= jdbc:mysql://localhost:3306/event_tickte_platform
spring.datasource.username=root
spring.datasource.password=anurag99

spring.jpa.hibernate.ddl-auto=update